FROM node:16-buster

RUN apt-get update && apt-get install -y postgis

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY package.json /home/node/app
COPY . /home/node/app

CMD ["sh","-c","npm install && npm run dev"]
EXPOSE 3000
