version: "3"
services:
  tool_db:
    restart: "no"
    ports:
      - "5432:5432"
      - "1521:1521"

  tool_simulator:
    build:
      context: ../herramienta-resiliencia-simulador #local clone of the model repo
      args:
        userpassword: ${MODEL_PASSWORD}
    image: tool_simulator_dev
    restart: "no"

  tool_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tool_server_dev
    restart: "no"
    volumes:
      - .:/home/node/app #dev volume
      - ${MODEL_OUPUTS_DIR}:/home/node/app/model_outputs
