version: "3"
services:
  geoserver:
    image: kartoza/geoserver:2.20.2
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ${GS_DATA_DIR}:/opt/geoserver/data_dir
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
    environment:
      - GEOSERVER_ADMIN_USER=${GS_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GS_PASS}
    networks:
      - server_net


  tool_server:
    environment:
      - GS_ENABLE=true
