version: "3"
services:
  tool_simulator:
    build:
      context: https://github.com/PEM-Humboldt/herramienta-resiliencia-simulador.git#main
      args:
        userpassword: ${MODEL_PASSWORD}
    image: tool_simulator
    container_name: tool_simulator
    volumes:
      - ${MODEL_OUPUTS_DIR}:/home/model/app/outputs
    restart: always
    networks:
      - server_net

  tool_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: tool_server
    container_name: tool_server
    ports:
      - "3000:3000"
    volumes:
      - ${MODEL_OUPUTS_DIR}:/home/node/app/model_outputs
    restart: always
    environment:
      - DB_HOST=tool_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GS_ENABLE=false
      - GS_USER=${GS_USER}
      - GS_PASS=${GS_PASS}
      - MODEL_PASSWORD=${MODEL_PASSWORD}
      - MODEL_PARAMS_PATH=/home/model/app/condiciones_iniciales/
    networks:
      - server_net

networks:
  server_net:
    driver: bridge
